In [2]:
import pandas as pd

In [3]:
import os

print(os.getcwd())

c:\Users\rashi\OneDrive\Desktop\my task

In [4]:
print(os.listdir())

['.vscode', 'archive.zip', 'calulator2.py', 'data.ipynb', 'dataanaly1.ipynb', 'ECOMM DATA.xlsx - Orders', 'password2.py', 'to do slist 1.py']

In [5]:
import os

file = "ECOMM DATA.xlsx - Orders"

print("Exists:", os.path.exists(file))
print("Is file:", os.path.isfile(file))
print("Is folder:", os.path.isdir(file))

Exists: True
Is file: False
Is folder: True

In [6]:
import os

print(os.listdir("ECOMM DATA.xlsx - Orders"))

['ECOMM DATA.xlsx - Orders.csv']

In [7]:
df = pd.read_csv("ECOMM DATA.xlsx - Orders/ECOMM DATA.xlsx - Orders.csv")

In [8]:
df.head()

,ROW ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Shipping Cost,Profit,Order Priority
0,26341,CA-2012-124891,31/7/2012,31/7/2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,933.57,762.1845,Critical
1,26341,IN-2013-77878,5/2/2013,7/2/2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,923.63,-288.7650,Critical
2,25330,IN-2013-71249,17/10/2013,18/10/2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,915.49,919.9710,Medium
3,13524,ES-2013-1579342,28/1/2013,30/1/2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,910.16,-96.5400,Medium
4,47221,SG-2013-4320,5/11/2013,6/11/2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,903.04,311.5200,Critical

In [11]:
df.shape

(51290, 24)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ROW ID          51290 non-null  int64
 1   Order ID        51290 non-null  str
 2   Order Date      51290 non-null  str
 3   Ship Date       51290 non-null  str
 4   Ship Mode       51290 non-null  str
 5   Customer ID     51290 non-null  str
 6   Customer Name   51290 non-null  str
 7   Segment         51290 non-null  str
 8   City            51290 non-null  str
 9   State           51290 non-null  str
 10  Country         51290 non-null  str
 11  Market          51290 non-null  str
 12  Postal Code     9994 non-null   float64
 13  Region          51290 non-null  str
 14  Product ID      51290 non-null  str
 15  Category        51290 non-null  str
 16  Sub-Category    51290 non-null  str
 17  Product Name    51290 non-null  str
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Shipping Cost   51290 non-null  float64
 22  Profit          51290 non-null  float64
 23  Order Priority  51290 non-null  str
dtypes: float64(5), int64(2), str(17)
memory usage: 9.4 MB

In [13]:
df.isnull().sum()

ROW ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Market                0
Postal Code       41296
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Shipping Cost         0
Profit                0
Order Priority        0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.describe()

,ROW ID,Postal Code,Sales,Quantity,Discount,Shipping Cost,Profit
count,51290.000000,9994.000000,51290.000000,51290.000000,51290.000000,51290.000000,51290.000000
mean,25645.383857,55190.379428,246.490581,3.476545,0.142908,26.375915,28.610982
std,14806.263170,32063.693350,487.565361,2.278766,0.212280,57.296804,174.340972
min,1.000000,1040.000000,0.444000,1.000000,0.000000,0.000000,-6599.978000
25%,12823.250000,23223.000000,30.758625,2.000000,0.000000,2.610000,0.000000
50%,25645.500000,56430.500000,85.053000,3.000000,0.000000,7.790000,9.240000
75%,38467.750000,90008.000000,251.053200,5.000000,0.200000,24.450000,36.810000
max,51290.000000,99301.000000,22638.480000,14.000000,0.850000,933.570000,8399.976000

In [16]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

C:\Users\rashi\AppData\Local\Temp\ipykernel_11420\2772104420.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Order Date"] = pd.to_datetime(df["Order Date"])
C:\Users\rashi\AppData\Local\Temp\ipykernel_11420\2772104420.py:2: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [17]:
df[["Order Date", "Ship Date"]].dtypes

Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [18]:
df["Postal Code"].value_counts(dropna=False).head(10)

Postal Code
NaN        41296
10035.0      263
10024.0      230
10009.0      229
94122.0      203
10011.0      193
94110.0      166
98105.0      165
19134.0      160
90049.0      151
Name: count, dtype: int64

In [19]:
df.dtypes

ROW ID                     int64
Order ID                     str
Order Date        datetime64[us]
Ship Date         datetime64[us]
Ship Mode                    str
Customer ID                  str
Customer Name                str
Segment                      str
City                         str
State                        str
Country                      str
Market                       str
Postal Code              float64
Region                       str
Product ID                   str
Category                     str
Sub-Category                 str
Product Name                 str
Sales                    float64
Quantity                   int64
Discount                 float64
Shipping Cost            float64
Profit                   float64
Order Priority               str
dtype: object

In [20]:
print("Negative Sales:", (df["Sales"] < 0).sum())
print("Negative Quantity:", (df["Quantity"] < 0).sum())
print("Negative Discount:", (df["Discount"] < 0).sum())
print("Negative Shipping Cost:", (df["Shipping Cost"] < 0).sum())
print("Negative Profit:", (df["Profit"] < 0).sum())

Negative Sales: 0
Negative Quantity: 0
Negative Discount: 0
Negative Shipping Cost: 0
Negative Profit: 12544

In [21]:
df["Profit"].describe()

count    51290.000000
mean        28.610982
std        174.340972
min      -6599.978000
25%          0.000000
50%          9.240000
75%         36.810000
max       8399.976000
Name: Profit, dtype: float64

In [22]:
(df["Quantity"] == 0).sum()

np.int64(0)

In [23]:
df["Discount"].describe()

count    51290.000000
mean         0.142908
std          0.212280
min          0.000000
25%          0.000000
50%          0.000000
75%          0.200000
max          0.850000
Name: Discount, dtype: float64

In [24]:
df["Shipping Cost"].describe()

count    51290.000000
mean        26.375915
std         57.296804
min          0.000000
25%          2.610000
50%          7.790000
75%         24.450000
max        933.570000
Name: Shipping Cost, dtype: float64

In [25]:
df["Order Priority"].value_counts()

Order Priority
Medium      29433
High        15501
Critical     3932
Low          2424
Name: count, dtype: int64

In [26]:
print("Ship Mode:", df["Ship Mode"].unique())
print("Segment:", df["Segment"].unique())
print("Category:", df["Category"].unique())
print("Region:", df["Region"].unique())

Ship Mode: <StringArray>
['Same Day', 'Second Class', 'First Class', 'Standard Class']
Length: 4, dtype: str
Segment: <StringArray>
['Consumer', 'Corporate', 'Home Office']
Length: 3, dtype: str
Category: <StringArray>
['Technology', 'Furniture', 'Office Supplies']
Length: 3, dtype: str
Region: <StringArray>
[          'East',        'Oceania',        'Central',         'Africa',
           'West',          'South',   'Central Asia',           'EMEA',
     'North Asia',          'North',      'Caribbean', 'Southeast Asia',
         'Canada']
Length: 13, dtype: str

In [27]:
df["Sub-Category"].value_counts()

Sub-Category
Binders        6152
Storage        5059
Art            4883
Paper          3538
Chairs         3434
Phones         3357
Furnishings    3170
Accessories    3075
Labels         2606
Envelopes      2435
Supplies       2425
Fasteners      2420
Bookcases      2411
Copiers        2223
Appliances     1755
Machines       1486
Tables          861
Name: count, dtype: int64

In [28]:
print("Missing Customer IDs:", df["Customer ID"].isnull().sum())
print("Missing Order IDs:", df["Order ID"].isnull().sum())
print("Missing Product IDs:", df["Product ID"].isnull().sum())

Missing Customer IDs: 0
Missing Order IDs: 0
Missing Product IDs: 0

In [29]:
df.isnull().sum()[df.isnull().sum() > 0]

Postal Code    41296
dtype: int64

In [9]:
df.to_csv("ECOMM_cleaned.csv", index=False)

In [10]:
import os

print(os.path.exists("ECOMM_cleaned.csv"))

True