In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("ECOMM_cleaned.csv")
df.head()

,ROW ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Shipping Cost,Profit,Order Priority
0,26341,CA-2012-124891,31/7/2012,31/7/2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,933.57,762.1845,Critical
1,26341,IN-2013-77878,5/2/2013,7/2/2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,923.63,-288.7650,Critical
2,25330,IN-2013-71249,17/10/2013,18/10/2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,915.49,919.9710,Medium
3,13524,ES-2013-1579342,28/1/2013,30/1/2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,910.16,-96.5400,Medium
4,47221,SG-2013-4320,5/11/2013,6/11/2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,903.04,311.5200,Critical

In [4]:
df.describe()
df.describe(include="object")

C:\Users\rashi\AppData\Local\Temp\ipykernel_10720\905123212.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Market,Region,Product ID,Category,Sub-Category,Product Name,Order Priority
count,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290,51290
unique,25035,1430,1464,4,1590,795,3,3636,1094,147,7,13,10292,3,17,3788,4
top,CA-2014-100111,18/6/2014,22/11/2014,Standard Class,PO-18850,Muhammed Yedwab,Consumer,New York City,California,United States,APAC,Central,OFF-AR-10003651,Office Supplies,Binders,Staples,Medium
freq,14,135,130,30775,97,108,26518,915,2001,9994,11002,11117,35,31273,6152,227,29433

In [5]:
df.groupby("Category")[["Sales", "Profit"]].sum().sort_values(
    "Sales", ascending=False
)

                        Sales        Profit
Category
Technology       4.744557e+06  663778.73318
Furniture        4.110874e+06  285204.72380
Office Supplies  3.787070e+06  518473.83430

In [6]:
df.groupby("Region")[["Sales", "Profit"]].sum().sort_values(
    "Sales", ascending=False
)

                       Sales        Profit
Region
Central         2.822303e+06  311403.98164
South           1.600907e+06  140355.76618
North           1.248166e+06  194597.95252
Oceania         1.100185e+06  120089.11200
Southeast Asia  8.844232e+05   17852.32900
North Asia      8.483098e+05  165578.42100
EMEA            8.061613e+05   43897.97100
Africa          7.837732e+05   88871.63100
Central Asia    7.528266e+05  132480.18700
West            7.254578e+05  108418.44890
East            6.787812e+05   91522.78000
Caribbean       3.242809e+05   34571.32104
Canada          6.692817e+04   17817.39000

In [7]:
df["Order Date"] = pd.to_datetime(df["Order Date"])

monthly_sales = df.groupby(
    df["Order Date"].dt.to_period("M")
)["Sales"].sum()

monthly_sales

C:\Users\rashi\AppData\Local\Temp\ipykernel_10720\3660064219.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Order Date"] = pd.to_datetime(df["Order Date"])

Order Date
2011-01     98898.48886
2011-02     91152.15698
2011-03    145729.36736
2011-04    116915.76418
2011-05    146747.83610
2011-06    215207.38022
2011-07    115510.41912
2011-08    207581.49122
2011-09    290214.45534
2011-10    199071.26404
2011-11    298496.53752
2011-12    333925.73460
2012-01    135780.72024
2012-02    100510.21698
2012-03    163076.77116
2012-04    161052.26952
2012-05    208364.89124
2012-06    256175.69842
2012-07    145236.78512
2012-08    303142.94238
2012-09    289389.16564
2012-10    252939.85020
2012-11    323512.41690
2012-12    338256.96660
2013-01    199185.90738
2013-02    167239.65040
2013-03    198594.03012
2013-04    177821.31684
2013-05    260498.56470
2013-06    396519.61190
2013-07    229928.95200
2013-08    326488.78936
2013-09    376619.24568
2013-10    293406.64288
2013-11    373989.36010
2013-12    405454.37802
2014-01    241268.55566
2014-02    184837.35556
2014-03    263100.77262
2014-04    242771.86130
2014-05    288401.04614
2014-06    401814.06310
2014-07    258705.68048
2014-08    456619.94236
2014-09    481157.24370
2014-10    422766.62916
2014-11    555279.02700
2014-12    503143.69348
Freq: M, Name: Sales, dtype: float64

In [8]:
highest_month = monthly_sales.idxmax()
highest_sales = monthly_sales.max()

lowest_month = monthly_sales.idxmin()
lowest_sales = monthly_sales.min()

print("Highest Sales Month:", highest_month)
print("Highest Sales:", highest_sales)

print("Lowest Sales Month:", lowest_month)
print("Lowest Sales:", lowest_sales)

Highest Sales Month: 2014-11
Highest Sales: 555279.027
Lowest Sales Month: 2011-02
Lowest Sales: 91152.15698

In [9]:
Q1 = df["Sales"].quantile(0.25)
Q3 = df["Sales"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[
    (df["Sales"] < lower_limit) |
    (df["Sales"] > upper_limit)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)
print("Number of Sales Outliers:", len(outliers))

Q1: 30.758625000000002
Q3: 251.0532
IQR: 220.294575
Lower Limit: -299.6832375
Upper Limit: 581.4950625
Number of Sales Outliers: 5655

In [10]:
Q1 = df["Sales"].quantile(0.25)
Q3 = df["Sales"].quantile(0.75)

IQR = Q3 - Q1

lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

outliers = df[
    (df["Sales"] < lower_limit) |
    (df["Sales"] > upper_limit)
]

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower Limit:", lower_limit)
print("Upper Limit:", upper_limit)
print("Number of Sales Outliers:", len(outliers))

Q1: 30.758625000000002
Q3: 251.0532
IQR: 220.294575
Lower Limit: -299.6832375
Upper Limit: 581.4950625
Number of Sales Outliers: 5655

In [11]:
profit_stats = df["Profit"].describe()

print(profit_stats)
loss_orders = (df["Profit"] < 0).sum()

print("Loss-making orders:", loss_orders)

count    51290.000000
mean        28.610982
std        174.340972
min      -6599.978000
25%          0.000000
50%          9.240000
75%         36.810000
max       8399.976000
Name: Profit, dtype: float64
Loss-making orders: 12544

In [12]:
df.groupby("Category")["Sales"].sum().sort_values(ascending=False)

Category
Technology         4.744557e+06
Furniture          4.110874e+06
Office Supplies    3.787070e+06
Name: Sales, dtype: float64

In [13]:
df.groupby("Category")["Profit"].sum().sort_values(ascending=False)

Category
Technology         663778.73318
Office Supplies    518473.83430
Furniture          285204.72380
Name: Profit, dtype: float64

In [14]:
df.groupby("Segment")["Sales"].sum().sort_values(ascending=False)

Segment
Consumer       6.507949e+06
Corporate      3.824698e+06
Home Office    2.309855e+06
Name: Sales, dtype: float64

In [15]:
df.groupby("Sub-Category")["Sales"].sum().sort_values(ascending=False).head(10)

Sub-Category
Phones         1.706824e+06
Copiers        1.509436e+06
Chairs         1.501682e+06
Bookcases      1.466572e+06
Storage        1.127086e+06
Appliances     1.011064e+06
Machines       7.790601e+05
Tables         7.570419e+05
Accessories    7.492370e+05
Binders        4.619115e+05
Name: Sales, dtype: float64

In [16]:
df.groupby("Sub-Category")["Profit"].sum().sort_values().head(10)

Sub-Category
Tables        -64083.3887
Fasteners      11525.4241
Labels         15010.5120
Supplies       22583.2631
Envelopes      29601.1163
Furnishings    46967.4255
Art            57953.9109
Machines       58867.8730
Paper          59207.6827
Binders        72449.8460
Name: Profit, dtype: float64

In [17]:
print("Total Sales:", df["Sales"].sum())
print("Total Profit:", df["Profit"].sum())
print("Average Sales:", df["Sales"].mean())
print("Average Profit:", df["Profit"].mean())
print("Total Quantity:", df["Quantity"].sum())

Total Sales: 12642501.90988
Total Profit: 1467457.29128
Average Sales: 246.4905812025736
Average Profit: 28.61098247767596
Total Quantity: 178312

In [18]:
segment_analysis = df.groupby("Segment")[["Sales", "Profit"]].sum().sort_values(
    "Sales", ascending=False
)

print(segment_analysis)

                    Sales        Profit
Segment
Consumer     6.507949e+06  749239.78206
Corporate    3.824698e+06  441208.32866
Home Office  2.309855e+06  277009.18056

In [19]:
region_profit = df.groupby("Region")["Profit"].sum().sort_values(ascending=False)

print(region_profit)

Region
Central           311403.98164
North             194597.95252
North Asia        165578.42100
South             140355.76618
Central Asia      132480.18700
Oceania           120089.11200
West              108418.44890
East               91522.78000
Africa             88871.63100
EMEA               43897.97100
Caribbean          34571.32104
Southeast Asia     17852.32900
Canada             17817.39000
Name: Profit, dtype: float64

In [20]:
print("Most Profitable Region:", region_profit.idxmax())
print("Highest Profit:", region_profit.max())

print("Least Profitable Region:", region_profit.idxmin())
print("Lowest Profit:", region_profit.min())

Most Profitable Region: Central
Highest Profit: 311403.98164
Least Profitable Region: Canada
Lowest Profit: 17817.39

In [21]:
product_profit = df.groupby("Product Name")["Profit"].sum().sort_values(ascending=False)

print("Top 10 Most Profitable Products:")
print(product_profit.head(10))

Top 10 Most Profitable Products:
Product Name
Canon imageCLASS 2200 Advanced Copier                       25199.9280
Cisco Smart Phone, Full Size                                17238.5206
Motorola Smart Phone, Full Size                             17027.1130
Hoover Stove, Red                                           11807.9690
Sauder Classic Bookcase, Traditional                        10672.0730
Harbour Creations Executive Leather Armchair, Adjustable    10427.3260
Nokia Smart Phone, Full Size                                 9938.1955
Cisco Smart Phone, with Caller ID                            9786.6408
Nokia Smart Phone, with Caller ID                            9465.3257
Belkin Router, USB                                           8955.0180
Name: Profit, dtype: float64

In [22]:
print("Top 10 Least Profitable Products:")
print(product_profit.tail(10))

Top 10 Least Profitable Products:
Product Name
Lesro Training Table, Rectangular                          -2581.2834
Bevis Wood Table, with Bottom Storage                      -2782.5880
Chromcraft Bull-Nose Wood Oval Conference Tables & Bases   -2876.1156
Rogers Lockers, Blue                                       -2893.4908
Bevis Computer Table, Fully Assembled                      -3509.5638
Bevis Round Table, Adjustable Height                       -3649.8940
Cubify CubeX 3D Printer Triple Head Print                  -3839.9904
Motorola Smart Phone, Cordless                             -4447.0380
Lexmark MX611dhe Monochrome Laser Printer                  -4589.9730
Cubify CubeX 3D Printer Double Head Print                  -8879.9704
Name: Profit, dtype: float64

In [23]:
print("===== EDA SUMMARY =====")

print("Total Sales:", df["Sales"].sum())
print("Total Profit:", df["Profit"].sum())
print("Average Sales:", df["Sales"].mean())
print("Average Profit:", df["Profit"].mean())

print("\nHighest Sales Category:")
print(df.groupby("Category")["Sales"].sum().idxmax())

print("\nHighest Profit Category:")
print(df.groupby("Category")["Profit"].sum().idxmax())

print("\nHighest Sales Region:")
print(df.groupby("Region")["Sales"].sum().idxmax())

print("\nHighest Profit Region:")
print(df.groupby("Region")["Profit"].sum().idxmax())

print("\nLoss-making Orders:")
print((df["Profit"] < 0).sum())

===== EDA SUMMARY =====
Total Sales: 12642501.90988
Total Profit: 1467457.29128
Average Sales: 246.4905812025736
Average Profit: 28.61098247767596

Highest Sales Category:
Technology

Highest Profit Category:
Technology

Highest Sales Region:
Central

Highest Profit Region:
Central

Loss-making Orders:
12544

In [24]:
correlation = df[["Sales", "Profit", "Quantity", "Discount", "Shipping Cost"]].corr()

print(correlation)

                  Sales    Profit  Quantity  Discount  Shipping Cost
Sales          1.000000  0.484918  0.313577 -0.086722       0.768073
Profit         0.484918  1.000000  0.104365 -0.316490       0.354441
Quantity       0.313577  0.104365  1.000000 -0.019875       0.272649
Discount      -0.086722 -0.316490 -0.019875  1.000000      -0.079056
Shipping Cost  0.768073  0.354441  0.272649 -0.079056       1.000000

In [25]:
top_products = (
    df.groupby("Product Name")["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print(top_products)

Product Name
Apple Smart Phone, Full Size                                86935.7786
Cisco Smart Phone, Full Size                                76441.5306
Motorola Smart Phone, Full Size                             73156.3030
Nokia Smart Phone, Full Size                                71904.5555
Canon imageCLASS 2200 Advanced Copier                       61599.8240
Hon Executive Leather Armchair, Adjustable                  58193.4841
Office Star Executive Leather Armchair, Adjustable          50661.6840
Harbour Creations Executive Leather Armchair, Adjustable    50121.5160
Samsung Smart Phone, Cordless                               48653.4600
Nokia Smart Phone, with Caller ID                           47877.7857
Name: Sales, dtype: float64

In [26]:
top_customers = (
    df.groupby(["Customer ID", "Customer Name"])["Sales"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

print(top_customers)

Customer ID  Customer Name
TA-21385     Tom Ashbrook        35668.12080
GT-14710     Greg Tran           34471.89028
TC-20980     Tamara Chand        34218.26900
SM-20320     Sean Miller         31125.29496
BW-11110     Bart Watters        30613.61650
HL-15040     Hunter Lopez        29664.23058
SE-20110     Sanjit Engle        29532.62502
PS-19045     Penelope Sewall     29252.31940
RB-19360     Raymond Buch        29197.63460
ZC-21910     Zuschuss Carroll    28472.81926
Name: Sales, dtype: float64

In [27]:
ship_analysis = df.groupby("Ship Mode")[["Sales", "Profit"]].sum().sort_values(
    "Sales", ascending=False
)

print(ship_analysis)

                       Sales        Profit
Ship Mode
Standard Class  7.578652e+06  890596.02120
Second Class    2.565672e+06  292583.52708
First Class     1.830976e+06  208104.67520
Same Day        6.672020e+05   76173.06780

In [28]:
print("Highest Sales Ship Mode:", ship_analysis["Sales"].idxmax())
print("Highest Profit Ship Mode:", ship_analysis["Profit"].idxmax())

Highest Sales Ship Mode: Standard Class
Highest Profit Ship Mode: Standard Class

In [29]:
market_analysis = (
    df.groupby("Market")[["Sales", "Profit"]]
    .sum()
    .sort_values("Sales", ascending=False)
)

print(market_analysis)

               Sales        Profit
Market
APAC    3.585744e+06  436000.04900
EU      2.938089e+06  372829.74150
US      2.297201e+06  286397.02170
LATAM   2.164605e+06  221643.48708
EMEA    8.061613e+05   43897.97100
Africa  7.837732e+05   88871.63100
Canada  6.692817e+04   17817.39000

In [30]:
print("Highest Sales Market:", market_analysis["Sales"].idxmax())
print("Highest Profit Market:", market_analysis["Profit"].idxmax())

Highest Sales Market: APAC
Highest Profit Market: APAC

In [31]:
corr = df[["Sales", "Profit", "Quantity", "Discount", "Shipping Cost"]].corr()

corr_pairs = corr.unstack().sort_values(ascending=False)

print(corr_pairs)

Sales          Sales            1.000000
Profit         Profit           1.000000
Shipping Cost  Shipping Cost    1.000000
Discount       Discount         1.000000
Quantity       Quantity         1.000000
Shipping Cost  Sales            0.768073
Sales          Shipping Cost    0.768073
Profit         Sales            0.484918
Sales          Profit           0.484918
Shipping Cost  Profit           0.354441
Profit         Shipping Cost    0.354441
Quantity       Sales            0.313577
Sales          Quantity         0.313577
Shipping Cost  Quantity         0.272649
Quantity       Shipping Cost    0.272649
Profit         Quantity         0.104365
Quantity       Profit           0.104365
               Discount        -0.019875
Discount       Quantity        -0.019875
               Shipping Cost   -0.079056
Shipping Cost  Discount        -0.079056
Discount       Sales           -0.086722
Sales          Discount        -0.086722
Profit         Discount        -0.316490
Discount       Profit          -0.316490
dtype: float64

In [32]:
eda_summary = pd.DataFrame({
    "Metric": [
        "Total Sales",
        "Total Profit",
        "Average Sales",
        "Average Profit",
        "Total Quantity",
        "Loss-making Orders"
    ],
    "Value": [
        df["Sales"].sum(),
        df["Profit"].sum(),
        df["Sales"].mean(),
        df["Profit"].mean(),
        df["Quantity"].sum(),
        (df["Profit"] < 0).sum()
    ]
})

eda_summary

               Metric         Value
0         Total Sales  1.264250e+07
1        Total Profit  1.467457e+06
2       Average Sales  2.464906e+02
3      Average Profit  2.861098e+01
4      Total Quantity  1.783120e+05
5  Loss-making Orders  1.254400e+04

In [33]:
category_counts = df["Category"].value_counts()

print(category_counts)

Category
Office Supplies    31273
Technology         10141
Furniture           9876
Name: count, dtype: int64

In [34]:
print("Most Common Category:", category_counts.idxmax())
print("Number of Orders:", category_counts.max())

Most Common Category: Office Supplies
Number of Orders: 31273

In [35]:
segment_counts = df["Segment"].value_counts()

print(segment_counts)

Segment
Consumer       26518
Corporate      15429
Home Office     9343
Name: count, dtype: int64

In [36]:
print("Most Common Segment:", segment_counts.idxmax())
print("Number of Records:", segment_counts.max())

Most Common Segment: Consumer
Number of Records: 26518

In [37]:
priority_counts = df["Order Priority"].value_counts()

print(priority_counts)

Order Priority
Medium      29433
High        15501
Critical     3932
Low          2424
Name: count, dtype: int64

In [38]:
print("Most Common Priority:", priority_counts.idxmax())
print("Number of Records:", priority_counts.max())

Most Common Priority: Medium
Number of Records: 29433

In [39]:
category_analysis = df.groupby("Category")[["Sales", "Profit", "Quantity"]].sum()

print(category_analysis)

                        Sales        Profit  Quantity
Category
Furniture        4.110874e+06  285204.72380     34954
Office Supplies  3.787070e+06  518473.83430    108182
Technology       4.744557e+06  663778.73318     35176

In [40]:
print("Highest Sales Category:", category_analysis["Sales"].idxmax())
print("Highest Profit Category:", category_analysis["Profit"].idxmax())
print("Highest Quantity Category:", category_analysis["Quantity"].idxmax())

Highest Sales Category: Technology
Highest Profit Category: Technology
Highest Quantity Category: Office Supplies

In [41]:
print("===== FINAL EDA FINDINGS =====")

print("1. Highest Sales Category:",
      df.groupby("Category")["Sales"].sum().idxmax())

print("2. Highest Profit Category:",
      df.groupby("Category")["Profit"].sum().idxmax())

print("3. Highest Sales Region:",
      df.groupby("Region")["Sales"].sum().idxmax())

print("4. Highest Profit Region:",
      df.groupby("Region")["Profit"].sum().idxmax())

print("5. Highest Sales Segment:",
      df.groupby("Segment")["Sales"].sum().idxmax())

print("6. Most Common Category:",
      df["Category"].value_counts().idxmax())

print("7. Loss-making Orders:",
      (df["Profit"] < 0).sum())

===== FINAL EDA FINDINGS =====
1. Highest Sales Category: Technology
2. Highest Profit Category: Technology
3. Highest Sales Region: Central
4. Highest Profit Region: Central
5. Highest Sales Segment: Consumer
6. Most Common Category: Office Supplies
7. Loss-making Orders: 12544

## EDA Business Insights

1. The Central region generated the highest overall sales and profit.
2. Sales generally increased over the years, showing an overall positive trend.
3. Sales were generally higher during the later months of the year.
4. Some orders generated negative profit, indicating loss-making transactions.
5. The dataset contains different customer segments, categories, regions, and shipping modes.
6. The analysis identified differences in sales and profitability across categories and regions.
7. Outlier analysis helped identify unusually high sales transactions.